//GLOBAL ACTIONS
export const CHANGE_STATE = "CHANGE_STATE";
export const RESET_STORE = "RESET_STORE";

//AUTH ACTIONS
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//LOCATION ACTIONS
export const GET_LOCATIONS = "GET_LOCATIONS";

//PERSON ACTIONS
export const SAVE_PERSON = "SAVE_PERSON";
export const GET_ALL_PEOPLE = "GET_ALL_PEOPLE";
export const DELETE_PERSON_BY_ID = "DELETE_PERSON_BY_ID";
export const SET_PERSON = "SET_PERSON";
export const EDIT_PERSON = "EDIT_PERSON";

//PERMIT ACTIONS
export const SAVE_PERMIT = "SAVE_PERMIT";
export const GET_PERMITS = "GET_PERMITS";
export const DELETE_PERMIT_BY_ID = "DELETE_PERMIT_BY_ID";
export const SET_PERMIT = "SET_PERMIT";
export const EDIT_PERMIT = "EDIT_PERMIT";
